# serializers.py (dalam aplikasi Anda)
from rest_framework import serializers

class PrediksiSerializer(serializers.Serializer):
    debtor_nik = serializers.CharField()
    debtor_name = serializers.CharField()
    debtor_gender = serializers.CharField()
    debtor_birth_place = serializers.CharField()
    debtor_age = serializers.IntegerField()
    debtor_zip = serializers.CharField()
    debtor_rt = serializers.CharField()
    debtor_rw = serializers.CharField()
    debtor_address = serializers.CharField()
    debtor_number = serializers.CharField()
    bulan_1 = serializers.IntegerField()
    bulan_2 = serializers.IntegerField()
    bulan_3 = serializers.IntegerField()
    bulan_4 = serializers.IntegerField()
    bulan_5 = serializers.IntegerField()
    bulan_6 = serializers.IntegerField()
    bulan_7 = serializers.IntegerField()
    bulan_8 = serializers.IntegerField()
    bulan_9 = serializers.IntegerField()
    bulan_10 = serializers.IntegerField()
    bulan_11 = serializers.IntegerField()
    bulan_12 = serializers.IntegerField()
    loan_amount = serializers.FloatField()
    tenor = serializers.IntegerField()
    billing_frequency = serializers.IntegerField()
    transaction_frequency = serializers.IntegerField()
    interest_rate = serializers.FloatField()
    other_credit = serializers.FloatField()
    monthly_income = serializers.FloatField()
    home_ownership = serializers.BooleanField()
    employment_status = serializers.CharField()
    employment_status_duration = serializers.IntegerField()
    public_records = serializers.IntegerField()
    contact_frequency = serializers.IntegerField()
    dti = serializers.FloatField()
    revolving_credit_balance = serializers.FloatField()
    occupation = serializers.CharField()
    financial_situation = serializers.CharField()
    delay_history = serializers.IntegerField()
    amount_of_late_days = serializers.IntegerField()
    number_of_dependents = serializers.IntegerField()
    number_of_vehicles = serializers.IntegerField()
    number_of_complaints = serializers.IntegerField()
    external_factors = serializers.FloatField()
    communication_channel = serializers.CharField()
    working_time = serializers.CharField()
    payment_patterns = serializers.CharField()
    payment_method = serializers.CharField()
    aging = serializers.FloatField()

class PrediksiResponseSerializer(serializers.Serializer):
    collection_difficulty_score = serializers.FloatField()
    collection_difficulty_category = serializers.CharField()